[package]
name = "rust_highered_videoweb"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.39"
csv = "1.3.1"
regex = "1.11.1"
reqwest = { version = "0.12.12", features = ["blocking", "json"] }
scraper = "0.22.0"
serde_json = "1.0.138"
url = "2.5.4"
